/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsOptional,
  ValidateNested,
  IsBoolean,
  IsString,
} from "class-validator";
import { AccountTypeWhereUniqueInput } from "../../accountType/base/AccountTypeWhereUniqueInput";
import { Type } from "class-transformer";
import { AccountUpdateManyWithoutAccountsInput } from "./AccountUpdateManyWithoutAccountsInput";
import { AccountWhereUniqueInput } from "./AccountWhereUniqueInput";
import { ScheduleEntryUpdateManyWithoutAccountsInput } from "./ScheduleEntryUpdateManyWithoutAccountsInput";
import { TransactionLineUpdateManyWithoutAccountsInput } from "./TransactionLineUpdateManyWithoutAccountsInput";
@InputType()
class AccountUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  accountNumber?: number;

  @ApiProperty({
    required: false,
    type: () => AccountTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountTypeWhereUniqueInput, {
    nullable: true,
  })
  accountType?: AccountTypeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AccountUpdateManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => AccountUpdateManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => AccountUpdateManyWithoutAccountsInput, {
    nullable: true,
  })
  childAccounts?: AccountUpdateManyWithoutAccountsInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isExternal?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isSummary?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountWhereUniqueInput, {
    nullable: true,
  })
  parent?: AccountWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ScheduleEntryUpdateManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => ScheduleEntryUpdateManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => ScheduleEntryUpdateManyWithoutAccountsInput, {
    nullable: true,
  })
  scheduleEntries?: ScheduleEntryUpdateManyWithoutAccountsInput;

  @ApiProperty({
    required: false,
    type: () => TransactionLineUpdateManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => TransactionLineUpdateManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => TransactionLineUpdateManyWithoutAccountsInput, {
    nullable: true,
  })
  transactionLines?: TransactionLineUpdateManyWithoutAccountsInput;
}
export { AccountUpdateInput };
