/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AccountService } from "../account.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AccountCreateInput } from "./AccountCreateInput";
import { AccountWhereInput } from "./AccountWhereInput";
import { AccountWhereUniqueInput } from "./AccountWhereUniqueInput";
import { AccountFindManyArgs } from "./AccountFindManyArgs";
import { AccountUpdateInput } from "./AccountUpdateInput";
import { Account } from "./Account";
import { EntityFindManyArgs } from "../../entity/base/EntityFindManyArgs";
import { Entity } from "../../entity/base/Entity";
import { EntityWhereUniqueInput } from "../../entity/base/EntityWhereUniqueInput";
import { ScheduleEntryFindManyArgs } from "../../scheduleEntry/base/ScheduleEntryFindManyArgs";
import { ScheduleEntry } from "../../scheduleEntry/base/ScheduleEntry";
import { ScheduleEntryWhereUniqueInput } from "../../scheduleEntry/base/ScheduleEntryWhereUniqueInput";
import { TransactionLineFindManyArgs } from "../../transactionLine/base/TransactionLineFindManyArgs";
import { TransactionLine } from "../../transactionLine/base/TransactionLine";
import { TransactionLineWhereUniqueInput } from "../../transactionLine/base/TransactionLineWhereUniqueInput";
@swagger.ApiBasicAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AccountControllerBase {
  constructor(
    protected readonly service: AccountService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Account })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: AccountCreateInput): Promise<Account> {
    return await this.service.create({
      data: {
        ...data,

        accountType: {
          connect: data.accountType,
        },

        parent: data.parent
          ? {
              connect: data.parent,
            }
          : undefined,
      },
      select: {
        accountNumber: true,

        accountType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isExternal: true,
        isSummary: true,
        name: true,

        parent: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Account] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(AccountFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Account[]> {
    const args = plainToClass(AccountFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        accountNumber: true,

        accountType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isExternal: true,
        isSummary: true,
        name: true,

        parent: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Account })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<Account | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        accountNumber: true,

        accountType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isExternal: true,
        isSummary: true,
        name: true,

        parent: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Account })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() data: AccountUpdateInput
  ): Promise<Account | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          accountType: {
            connect: data.accountType,
          },

          parent: data.parent
            ? {
                connect: data.parent,
              }
            : undefined,
        },
        select: {
          accountNumber: true,

          accountType: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          isExternal: true,
          isSummary: true,
          name: true,

          parent: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Account })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<Account | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          accountNumber: true,

          accountType: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          isExternal: true,
          isSummary: true,
          name: true,

          parent: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/childAccounts")
  @ApiNestedQuery(AccountFindManyArgs)
  async findManyChildAccounts(
    @common.Req() request: Request,
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<Account[]> {
    const query = plainToClass(AccountFindManyArgs, request.query);
    const results = await this.service.findChildAccounts(params.id, {
      ...query,
      select: {
        accountNumber: true,

        accountType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isExternal: true,
        isSummary: true,
        name: true,

        parent: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/childAccounts")
  async connectChildAccounts(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: AccountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      childAccounts: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/childAccounts")
  async updateChildAccounts(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: AccountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      childAccounts: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/childAccounts")
  async disconnectChildAccounts(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: AccountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      childAccounts: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Entity",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/entities")
  @ApiNestedQuery(EntityFindManyArgs)
  async findManyEntities(
    @common.Req() request: Request,
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<Entity[]> {
    const query = plainToClass(EntityFindManyArgs, request.query);
    const results = await this.service.findEntities(params.id, {
      ...query,
      select: {
        createdAt: true,
        data: true,

        defaultAccount: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/entities")
  async connectEntities(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: EntityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entities: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/entities")
  async updateEntities(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: EntityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entities: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/entities")
  async disconnectEntities(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: EntityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entities: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ScheduleEntry",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/scheduleEntries")
  @ApiNestedQuery(ScheduleEntryFindManyArgs)
  async findManyScheduleEntries(
    @common.Req() request: Request,
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<ScheduleEntry[]> {
    const query = plainToClass(ScheduleEntryFindManyArgs, request.query);
    const results = await this.service.findScheduleEntries(params.id, {
      ...query,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        amount: true,
        createdAt: true,

        createdTransactionLine: {
          select: {
            id: true,
          },
        },

        generateDate: true,
        id: true,
        memo: true,
        postDate: true,
        status: true,

        transactionSchedule: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/scheduleEntries")
  async connectScheduleEntries(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: ScheduleEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scheduleEntries: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/scheduleEntries")
  async updateScheduleEntries(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: ScheduleEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scheduleEntries: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/scheduleEntries")
  async disconnectScheduleEntries(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: ScheduleEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scheduleEntries: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TransactionLine",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/transactionLines")
  @ApiNestedQuery(TransactionLineFindManyArgs)
  async findManyTransactionLines(
    @common.Req() request: Request,
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<TransactionLine[]> {
    const query = plainToClass(TransactionLineFindManyArgs, request.query);
    const results = await this.service.findTransactionLines(params.id, {
      ...query,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        credit: true,
        data: true,
        debit: true,

        entity: {
          select: {
            id: true,
          },
        },

        id: true,
        isReconciled: true,
        memo: true,

        transaction: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/transactionLines")
  async connectTransactionLines(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: TransactionLineWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactionLines: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/transactionLines")
  async updateTransactionLines(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: TransactionLineWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactionLines: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/transactionLines")
  async disconnectTransactionLines(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: TransactionLineWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactionLines: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
