/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsJSON,
  IsOptional,
  IsString,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ScheduleEntryCreateNestedManyWithoutTransactionSchedulesInput } from "./ScheduleEntryCreateNestedManyWithoutTransactionSchedulesInput";
import { Type } from "class-transformer";
import { EnumTransactionScheduleScheduleType } from "./EnumTransactionScheduleScheduleType";
import { EnumTransactionScheduleStatus } from "./EnumTransactionScheduleStatus";
@InputType()
class TransactionScheduleCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  data?: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => ScheduleEntryCreateNestedManyWithoutTransactionSchedulesInput,
  })
  @ValidateNested()
  @Type(() => ScheduleEntryCreateNestedManyWithoutTransactionSchedulesInput)
  @IsOptional()
  @Field(() => ScheduleEntryCreateNestedManyWithoutTransactionSchedulesInput, {
    nullable: true,
  })
  scheduleEntries?: ScheduleEntryCreateNestedManyWithoutTransactionSchedulesInput;

  @ApiProperty({
    required: true,
    enum: EnumTransactionScheduleScheduleType,
  })
  @IsEnum(EnumTransactionScheduleScheduleType)
  @Field(() => EnumTransactionScheduleScheduleType)
  scheduleType!:
    | "Loan"
    | "Amortization"
    | "Depreciation"
    | "Expense"
    | "Income";

  @ApiProperty({
    required: false,
    enum: EnumTransactionScheduleStatus,
  })
  @IsEnum(EnumTransactionScheduleStatus)
  @IsOptional()
  @Field(() => EnumTransactionScheduleStatus, {
    nullable: true,
  })
  status?:
    | "New"
    | "NotStarted"
    | "InProgress"
    | "PendingUpdate"
    | "FailedScheduleGeneration"
    | "Error"
    | "Complete"
    | "FailedTransactionGeneration"
    | null;
}
export { TransactionScheduleCreateInput };
