/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TransactionScheduleService } from "../transactionSchedule.service";
import { Public } from "../../decorators/public.decorator";
import { TransactionScheduleCreateInput } from "./TransactionScheduleCreateInput";
import { TransactionScheduleWhereInput } from "./TransactionScheduleWhereInput";
import { TransactionScheduleWhereUniqueInput } from "./TransactionScheduleWhereUniqueInput";
import { TransactionScheduleFindManyArgs } from "./TransactionScheduleFindManyArgs";
import { TransactionScheduleUpdateInput } from "./TransactionScheduleUpdateInput";
import { TransactionSchedule } from "./TransactionSchedule";
import { ScheduleEntryFindManyArgs } from "../../scheduleEntry/base/ScheduleEntryFindManyArgs";
import { ScheduleEntry } from "../../scheduleEntry/base/ScheduleEntry";
import { ScheduleEntryWhereUniqueInput } from "../../scheduleEntry/base/ScheduleEntryWhereUniqueInput";
@swagger.ApiBasicAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TransactionScheduleControllerBase {
  constructor(
    protected readonly service: TransactionScheduleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TransactionSchedule })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: TransactionScheduleCreateInput
  ): Promise<TransactionSchedule> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        data: true,
        id: true,
        name: true,
        scheduleType: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [TransactionSchedule] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(TransactionScheduleFindManyArgs)
  async findMany(
    @common.Req() request: Request
  ): Promise<TransactionSchedule[]> {
    const args = plainToClass(TransactionScheduleFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        data: true,
        id: true,
        name: true,
        scheduleType: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TransactionSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: TransactionScheduleWhereUniqueInput
  ): Promise<TransactionSchedule | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        data: true,
        id: true,
        name: true,
        scheduleType: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @Public()
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TransactionSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: TransactionScheduleWhereUniqueInput,
    @common.Body() data: TransactionScheduleUpdateInput
  ): Promise<TransactionSchedule | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          data: true,
          id: true,
          name: true,
          scheduleType: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TransactionSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: TransactionScheduleWhereUniqueInput
  ): Promise<TransactionSchedule | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          data: true,
          id: true,
          name: true,
          scheduleType: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Get("/:id/scheduleEntries")
  @ApiNestedQuery(ScheduleEntryFindManyArgs)
  async findManyScheduleEntries(
    @common.Req() request: Request,
    @common.Param() params: TransactionScheduleWhereUniqueInput
  ): Promise<ScheduleEntry[]> {
    const query = plainToClass(ScheduleEntryFindManyArgs, request.query);
    const results = await this.service.findScheduleEntries(params.id, {
      ...query,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        amount: true,
        createdAt: true,

        createdTransactionLine: {
          select: {
            id: true,
          },
        },

        generateDate: true,
        id: true,
        memo: true,
        postDate: true,
        status: true,

        transactionSchedule: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @Public()
  @common.Post("/:id/scheduleEntries")
  async connectScheduleEntries(
    @common.Param() params: TransactionScheduleWhereUniqueInput,
    @common.Body() body: ScheduleEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scheduleEntries: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @Public()
  @common.Patch("/:id/scheduleEntries")
  async updateScheduleEntries(
    @common.Param() params: TransactionScheduleWhereUniqueInput,
    @common.Body() body: ScheduleEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scheduleEntries: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @Public()
  @common.Delete("/:id/scheduleEntries")
  async disconnectScheduleEntries(
    @common.Param() params: TransactionScheduleWhereUniqueInput,
    @common.Body() body: ScheduleEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scheduleEntries: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
