/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Public } from "../../decorators/public.decorator";
import { CreateTransactionLineArgs } from "./CreateTransactionLineArgs";
import { UpdateTransactionLineArgs } from "./UpdateTransactionLineArgs";
import { DeleteTransactionLineArgs } from "./DeleteTransactionLineArgs";
import { TransactionLineFindManyArgs } from "./TransactionLineFindManyArgs";
import { TransactionLineFindUniqueArgs } from "./TransactionLineFindUniqueArgs";
import { TransactionLine } from "./TransactionLine";
import { ScheduleEntryFindManyArgs } from "../../scheduleEntry/base/ScheduleEntryFindManyArgs";
import { ScheduleEntry } from "../../scheduleEntry/base/ScheduleEntry";
import { Account } from "../../account/base/Account";
import { Entity } from "../../entity/base/Entity";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionLineService } from "../transactionLine.service";

@graphql.Resolver(() => TransactionLine)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TransactionLineResolverBase {
  constructor(
    protected readonly service: TransactionLineService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @graphql.Query(() => MetaQueryPayload)
  async _transactionLinesMeta(
    @graphql.Args() args: TransactionLineFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @Public()
  @graphql.Query(() => [TransactionLine])
  async transactionLines(
    @graphql.Args() args: TransactionLineFindManyArgs
  ): Promise<TransactionLine[]> {
    return this.service.findMany(args);
  }

  @Public()
  @graphql.Query(() => TransactionLine, { nullable: true })
  async transactionLine(
    @graphql.Args() args: TransactionLineFindUniqueArgs
  ): Promise<TransactionLine | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @Public()
  @graphql.Mutation(() => TransactionLine)
  async createTransactionLine(
    @graphql.Args() args: CreateTransactionLineArgs
  ): Promise<TransactionLine> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        account: {
          connect: args.data.account,
        },

        entity: args.data.entity
          ? {
              connect: args.data.entity,
            }
          : undefined,

        transaction: {
          connect: args.data.transaction,
        },
      },
    });
  }

  @Public()
  @graphql.Mutation(() => TransactionLine)
  async updateTransactionLine(
    @graphql.Args() args: UpdateTransactionLineArgs
  ): Promise<TransactionLine | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          account: {
            connect: args.data.account,
          },

          entity: args.data.entity
            ? {
                connect: args.data.entity,
              }
            : undefined,

          transaction: {
            connect: args.data.transaction,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @graphql.Mutation(() => TransactionLine)
  async deleteTransactionLine(
    @graphql.Args() args: DeleteTransactionLineArgs
  ): Promise<TransactionLine | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @graphql.ResolveField(() => [ScheduleEntry])
  async createdFromSchedule(
    @graphql.Parent() parent: TransactionLine,
    @graphql.Args() args: ScheduleEntryFindManyArgs
  ): Promise<ScheduleEntry[]> {
    const results = await this.service.findCreatedFromSchedule(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @Public()
  @graphql.ResolveField(() => Account, { nullable: true })
  async account(
    @graphql.Parent() parent: TransactionLine
  ): Promise<Account | null> {
    const result = await this.service.getAccount(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @Public()
  @graphql.ResolveField(() => Entity, { nullable: true })
  async entity(
    @graphql.Parent() parent: TransactionLine
  ): Promise<Entity | null> {
    const result = await this.service.getEntity(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @Public()
  @graphql.ResolveField(() => Transaction, { nullable: true })
  async transaction(
    @graphql.Parent() parent: TransactionLine
  ): Promise<Transaction | null> {
    const result = await this.service.getTransaction(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
