/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TransactionLineService } from "../transactionLine.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TransactionLineCreateInput } from "./TransactionLineCreateInput";
import { TransactionLineWhereInput } from "./TransactionLineWhereInput";
import { TransactionLineWhereUniqueInput } from "./TransactionLineWhereUniqueInput";
import { TransactionLineFindManyArgs } from "./TransactionLineFindManyArgs";
import { TransactionLineUpdateInput } from "./TransactionLineUpdateInput";
import { TransactionLine } from "./TransactionLine";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TransactionLineControllerBase {
  constructor(
    protected readonly service: TransactionLineService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TransactionLine",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TransactionLine })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: TransactionLineCreateInput
  ): Promise<TransactionLine> {
    return await this.service.create({
      data: {
        ...data,

        account: {
          connect: data.account,
        },

        transaction: {
          connect: data.transaction,
        },
      },
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        credit: true,
        data: true,
        debit: true,
        id: true,
        isReconciled: true,
        memo: true,

        transaction: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TransactionLine",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [TransactionLine] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(TransactionLineFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<TransactionLine[]> {
    const args = plainToClass(TransactionLineFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        credit: true,
        data: true,
        debit: true,
        id: true,
        isReconciled: true,
        memo: true,

        transaction: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TransactionLine",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TransactionLine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: TransactionLineWhereUniqueInput
  ): Promise<TransactionLine | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        credit: true,
        data: true,
        debit: true,
        id: true,
        isReconciled: true,
        memo: true,

        transaction: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TransactionLine",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TransactionLine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: TransactionLineWhereUniqueInput,
    @common.Body() data: TransactionLineUpdateInput
  ): Promise<TransactionLine | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          account: {
            connect: data.account,
          },

          transaction: {
            connect: data.transaction,
          },
        },
        select: {
          account: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          credit: true,
          data: true,
          debit: true,
          id: true,
          isReconciled: true,
          memo: true,

          transaction: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "TransactionLine",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TransactionLine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: TransactionLineWhereUniqueInput
  ): Promise<TransactionLine | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          account: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          credit: true,
          data: true,
          debit: true,
          id: true,
          isReconciled: true,
          memo: true,

          transaction: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
