/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  IsString,
  ValidateNested,
} from "class-validator";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { CurrencyWhereUniqueInput } from "../../currency/base/CurrencyWhereUniqueInput";
import { TransactionCreateNestedManyWithoutBooksInput } from "./TransactionCreateNestedManyWithoutBooksInput";
@InputType()
class BookCreateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isPrimary?: boolean | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  owner?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: () => CurrencyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CurrencyWhereUniqueInput)
  @Field(() => CurrencyWhereUniqueInput)
  primaryCurrency!: CurrencyWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutBooksInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutBooksInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutBooksInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutBooksInput;
}
export { BookCreateInput };
