/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import {
  ValidateNested,
  IsNumber,
  IsOptional,
  IsDate,
  IsString,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { TransactionLineWhereUniqueInput } from "../../transactionLine/base/TransactionLineWhereUniqueInput";
import { EnumScheduleEntryStatus } from "./EnumScheduleEntryStatus";
import { TransactionScheduleWhereUniqueInput } from "../../transactionSchedule/base/TransactionScheduleWhereUniqueInput";
@InputType()
class ScheduleEntryCreateInput {
  @ApiProperty({
    required: true,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @Field(() => AccountWhereUniqueInput)
  account!: AccountWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  amount!: number;

  @ApiProperty({
    required: false,
    type: () => TransactionLineWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TransactionLineWhereUniqueInput)
  @IsOptional()
  @Field(() => TransactionLineWhereUniqueInput, {
    nullable: true,
  })
  createdTransactionLine?: TransactionLineWhereUniqueInput | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  generateDate!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  memo?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  postDate?: Date | null;

  @ApiProperty({
    required: true,
    enum: EnumScheduleEntryStatus,
  })
  @IsEnum(EnumScheduleEntryStatus)
  @Field(() => EnumScheduleEntryStatus)
  status!:
    | "NotStarted"
    | "PendingTransactionCreation"
    | "TransactionCreated"
    | "Error";

  @ApiProperty({
    required: true,
    type: () => TransactionScheduleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TransactionScheduleWhereUniqueInput)
  @Field(() => TransactionScheduleWhereUniqueInput)
  transactionSchedule!: TransactionScheduleWhereUniqueInput;
}
export { ScheduleEntryCreateInput };
