/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ScheduleEntryService } from "../scheduleEntry.service";
import { Public } from "../../decorators/public.decorator";
import { ScheduleEntryCreateInput } from "./ScheduleEntryCreateInput";
import { ScheduleEntryWhereInput } from "./ScheduleEntryWhereInput";
import { ScheduleEntryWhereUniqueInput } from "./ScheduleEntryWhereUniqueInput";
import { ScheduleEntryFindManyArgs } from "./ScheduleEntryFindManyArgs";
import { ScheduleEntryUpdateInput } from "./ScheduleEntryUpdateInput";
import { ScheduleEntry } from "./ScheduleEntry";
@swagger.ApiBasicAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ScheduleEntryControllerBase {
  constructor(
    protected readonly service: ScheduleEntryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ScheduleEntry })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ScheduleEntryCreateInput
  ): Promise<ScheduleEntry> {
    return await this.service.create({
      data: {
        ...data,

        account: {
          connect: data.account,
        },

        createdTransactionLine: data.createdTransactionLine
          ? {
              connect: data.createdTransactionLine,
            }
          : undefined,

        transactionSchedule: {
          connect: data.transactionSchedule,
        },
      },
      select: {
        account: {
          select: {
            id: true,
          },
        },

        amount: true,
        createdAt: true,

        createdTransactionLine: {
          select: {
            id: true,
          },
        },

        generateDate: true,
        id: true,
        memo: true,
        postDate: true,
        status: true,

        transactionSchedule: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [ScheduleEntry] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ScheduleEntryFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<ScheduleEntry[]> {
    const args = plainToClass(ScheduleEntryFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        amount: true,
        createdAt: true,

        createdTransactionLine: {
          select: {
            id: true,
          },
        },

        generateDate: true,
        id: true,
        memo: true,
        postDate: true,
        status: true,

        transactionSchedule: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ScheduleEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ScheduleEntryWhereUniqueInput
  ): Promise<ScheduleEntry | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        amount: true,
        createdAt: true,

        createdTransactionLine: {
          select: {
            id: true,
          },
        },

        generateDate: true,
        id: true,
        memo: true,
        postDate: true,
        status: true,

        transactionSchedule: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @Public()
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ScheduleEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ScheduleEntryWhereUniqueInput,
    @common.Body() data: ScheduleEntryUpdateInput
  ): Promise<ScheduleEntry | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          account: {
            connect: data.account,
          },

          createdTransactionLine: data.createdTransactionLine
            ? {
                connect: data.createdTransactionLine,
              }
            : undefined,

          transactionSchedule: {
            connect: data.transactionSchedule,
          },
        },
        select: {
          account: {
            select: {
              id: true,
            },
          },

          amount: true,
          createdAt: true,

          createdTransactionLine: {
            select: {
              id: true,
            },
          },

          generateDate: true,
          id: true,
          memo: true,
          postDate: true,
          status: true,

          transactionSchedule: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ScheduleEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ScheduleEntryWhereUniqueInput
  ): Promise<ScheduleEntry | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          account: {
            select: {
              id: true,
            },
          },

          amount: true,
          createdAt: true,

          createdTransactionLine: {
            select: {
              id: true,
            },
          },

          generateDate: true,
          id: true,
          memo: true,
          postDate: true,
          status: true,

          transactionSchedule: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
