/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BookCreateNestedManyWithoutTransactionsInput } from "./BookCreateNestedManyWithoutTransactionsInput";
import { ValidateNested, IsOptional, IsJSON, IsDate } from "class-validator";
import { Type } from "class-transformer";
import { JobWhereUniqueInput } from "../../job/base/JobWhereUniqueInput";
import { CurrencyWhereUniqueInput } from "../../currency/base/CurrencyWhereUniqueInput";
import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { TransactionLineCreateNestedManyWithoutTransactionsInput } from "./TransactionLineCreateNestedManyWithoutTransactionsInput";
@InputType()
class TransactionCreateInput {
  @ApiProperty({
    required: true,
    type: () => BookCreateNestedManyWithoutTransactionsInput,
  })
  @ValidateNested()
  @Type(() => BookCreateNestedManyWithoutTransactionsInput)
  @IsOptional()
  @Field(() => BookCreateNestedManyWithoutTransactionsInput, {
    nullable: true,
  })
  book?: BookCreateNestedManyWithoutTransactionsInput;

  @ApiProperty({
    required: false,
    type: () => JobWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => JobWhereUniqueInput)
  @IsOptional()
  @Field(() => JobWhereUniqueInput, {
    nullable: true,
  })
  createdFromJob?: JobWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: () => CurrencyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CurrencyWhereUniqueInput)
  @Field(() => CurrencyWhereUniqueInput)
  currency!: CurrencyWhereUniqueInput;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  data?: InputJsonValue;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  trandate!: Date;

  @ApiProperty({
    required: false,
    type: () => TransactionLineCreateNestedManyWithoutTransactionsInput,
  })
  @ValidateNested()
  @Type(() => TransactionLineCreateNestedManyWithoutTransactionsInput)
  @IsOptional()
  @Field(() => TransactionLineCreateNestedManyWithoutTransactionsInput, {
    nullable: true,
  })
  transactionLines?: TransactionLineCreateNestedManyWithoutTransactionsInput;
}
export { TransactionCreateInput };
