/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BookUpdateManyWithoutTransactionsInput } from "./BookUpdateManyWithoutTransactionsInput";
import { ValidateNested, IsOptional, IsDate } from "class-validator";
import { Type } from "class-transformer";
import { CurrencyWhereUniqueInput } from "../../currency/base/CurrencyWhereUniqueInput";
import { TransactionLineUpdateManyWithoutTransactionsInput } from "./TransactionLineUpdateManyWithoutTransactionsInput";
@InputType()
class TransactionUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BookUpdateManyWithoutTransactionsInput,
  })
  @ValidateNested()
  @Type(() => BookUpdateManyWithoutTransactionsInput)
  @IsOptional()
  @Field(() => BookUpdateManyWithoutTransactionsInput, {
    nullable: true,
  })
  book?: BookUpdateManyWithoutTransactionsInput;

  @ApiProperty({
    required: false,
    type: () => CurrencyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CurrencyWhereUniqueInput)
  @IsOptional()
  @Field(() => CurrencyWhereUniqueInput, {
    nullable: true,
  })
  currency?: CurrencyWhereUniqueInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  trandate?: Date;

  @ApiProperty({
    required: false,
    type: () => TransactionLineUpdateManyWithoutTransactionsInput,
  })
  @ValidateNested()
  @Type(() => TransactionLineUpdateManyWithoutTransactionsInput)
  @IsOptional()
  @Field(() => TransactionLineUpdateManyWithoutTransactionsInput, {
    nullable: true,
  })
  transactionLines?: TransactionLineUpdateManyWithoutTransactionsInput;
}
export { TransactionUpdateInput };
